### ISSUE TITLE
Window width setting

### ISSUE THREAD

**Issue by robcsi** [q335r49/microviche#2]
Hi,

I'd also like to be able to set the width of a window, or have the possibility to change to default width of all the windows.
The purpose would be to use the plugin with many source code files for programming.

Is this possible?

Thanks,
robcsi

**Comment by q335r49** [comment]
Hey rob,

It's hidden under the "Edit split" setting, F10-E, there should be a prompt to set the column width.

You can automated this by playing with the t:txb.size variable, whcih is the list of all column widths in order. Eg,

for i in len(t:txb.size)
   let t:txb.size[i]=120
endfor.

Thanks,

Leon

**Comment by robcsi** [comment]
Cool, thanks a lot. 
It works. :)
