### ISSUE TITLE
Function keys not reliable on all systems

### ISSUE THREAD

**Issue by NewAlexandria** [q335r49/microviche#3]
I work in an environment where the function keys are already hijacked by other things - so pressing them never makes it Vim.  I currently patch the code to allow my own key bindings.  Would be great if you would support remapping.

I'd say work on features and stability, first, though.  You have the chance for an epic niche community.

**Comment by q335r49** [comment]
Thanks for trying it out!

Yes, that's a good suggestion. I'm actually working on a UI to change the settings in-script (in the other branch), so hopefully I can provide a way to change the hotkeys in-script in the next version. (That is, without overloading the help file with explanations of function calls, etc.)

**Comment by NewAlexandria** [comment]
Sounds great!  Thanks for your creativity on this
